# Redis 8.2.x：开启 AOF，采用每秒 fsync
appendonly yes
appendfilename "appendonly.aof"
appenddirname "appendonlydir"
appendfsync everysec

# 其他策略只能择一启用
# appendfsync always
# appendfsync no

# 默认允许在后台保存或重写期间继续 fsync
no-appendfsync-on-rewrite no
# Redis 7.0 起使用多文件 AOF，基础文件默认采用 RDB 格式
aof-use-rdb-preamble yes
